config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'topics#index'

  get "/register", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :topics, only: [:index, :show, :new, :create, :edit, :update] do 
    member do 
      post :vote
    end
    resources :comments, only: [:create] do 
      member do 
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show]

  resources :users, only: [:create, :show, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :topic_categories
  has_many :topics, through: :topic_categories

  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :topic
  has_many :votes, as: :voteable

  validates :body, presence: true

  def total_votes
    up_votes - down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :topic_categories
  has_many :categories, through: :topic_categories
  has_many :votes, as: :voteable

  validates :title, presence: true
  validates :content, presence: true

  def total_votes
    up_votes - down_votes
  end

  def up_votes
    self.votes.where(vote: true).size
  end

  def down_votes
    self.votes.where(vote: false).size
  end
end 

app/models/topic_category.rb
class TopicCategory < ActiveRecord::Base
  belongs_to :topic 
  belongs_to :category 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :topics
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, on: :create, length: { minimum: 5 }
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user 
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :user, scope: :voteable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :require_user, :access_denied

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user 
    access_denied unless logged_in?
  end

  def access_denied
    flash[:error] = "This action is not allowed!"
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "New category was created."
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def create
    @topic = Topic.find(params[:topic_id])
    @comment = @topic.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Your comment was created."
      redirect_to topic_path(@topic)
    else
      render 'topics/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, user: current_user, vote: params[:vote])
    respond_to do |format|
      format.html do 
        if @vote.valid?
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You can only vote once for this comment."
        end
        redirect_to :back    
      end
      format.js
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      flash[:notice] = "You just logged in."
      redirect_to root_path
    else
      flash[:error] = "There were something wrong with your username or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logout."
    redirect_to root_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :vote]
  before_action :require_user, only: [:new, :create, :edit, :update, :vote]
  before_action :require_creator, only: [:edit, :update]

  def index
    @topics = Topic.all.sort_by { |topic| topic.total_votes }.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user = current_user
    if @topic.save
      flash[:notice] = "Your new topic was created!"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit   
  end

  def update
    if @topic.update_attributes(topic_params)
      flash[:notice] = 'Your topic was saved.'
      redirect_to topic_path
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @topic, vote: params[:vote], user: current_user)

    respond_to do |format|
      format.html do 
        if @vote.valid?
          flash[:notice] = "You vote was counted!"
        else
          flash[:error] = "You can only vote once for <strong>#{@topic.title}</strong>".html_safe
        end
        redirect_to :back
      end
      format.js
    end
  end

  private
    def topic_params
      params.require(:topic).permit(:title, :content, category_ids: [])
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end

    def require_creator
      access_denied if current_user != @topic.user  
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      flash[:notice] = "New user was created."
      redirect_to root_path
    else
      render :new 
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = 'Profile was updated.'
      redirect_to user_path
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user =  User.find(params[:id])
    end

    def require_same_user
      access_denied if current_user != @user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a new category' %>

<%= render 'shared/error', obj: @category %>

<div class="well">
  <%= form_for @category do |f| %>
    <div class="content-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Topics', topics_path) + " &raquo; #{@category.name}".html_safe %>

<%= render 'shared/content_title', title: header %>

<% @category.topics.each do |topic| %>
  <%= render 'topics/topic', topic: topic %>
<% end %>

app/views/comments/_comment.html.erb
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_topic_comment_path(comment.topic, comment, vote: true), method:'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
    <% end %><br>
    <span id="comment_<%= comment.id %>_vote"><%= pluralize(comment.total_votes, 'vote') %></span><br>
    <% if logged_in? %>
      <%= link_to vote_topic_comment_path(comment.topic, comment, vote: false), method:'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="well span8">
    <p><em>"<%= comment.body %>"</em></p> 
    <span class="quiet">by</span> 
    <%= link_to comment.user.username, user_path(comment.user) %> 
    <small>at <%= comment.created_at %></small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $("#comment_<%= @comment.id %>_vote").html("<%= pluralize(@comment.total_votes, 'vote') %>");
<% else %>
  alert("You can only vote once for this comment!");
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Ruby Canada", root_path, :class => 'brand' %>
  </li>
</ul>

<div class="btn-group nav_item">
  <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
    Categories
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <% Category.all.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
    <% end %>
    <% if logged_in? %>
      <li class="divider"></li>
      <li>
        <%= link_to(new_category_path) do %>
          <i class="icon-plus"></i>
          New Category
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<% if logged_in? %>
  <div class='nav_item'>
    <%= link_to 'New Topic', new_topic_path, class: 'btn btn-small btn-success' %>
  </div>

  <div class="btn-group nav_item">
    <a class="btn btn-small dropdown-toggle" data-toggle="dropdown" href="#">
      <%= current_user.username%>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
        <%= link_to(edit_user_path(current_user)) do %>
          <i class="icon-pencil"></i>
          Edit profile
        <% end %>
      </li>
      <li>
        <%= link_to(user_path(current_user)) do %>
          <i class="icon-user"></i>
          View profile
        <% end %>
      </li>
      <li>
        <%= link_to(logout_path) do %>
          <i class="icon-arrow-left"></i>
          Logout
        <% end %>
      </li>
    </ul>
  </div>
<% else %>
  <div class='nav_item'>
    <%= link_to 'Register', register_path, class: 'btn btn-small btn-success' %>
  </div>

  <div class='nav_item'>
    <%= link_to 'Login', login_path, class: 'btn btn-small' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ruby Canada</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title %>
  <hr>
</p>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-error span8">
      <h5>There were some errors:</h5>
      <% obj.errors.full_messages.each do |msg| %>
        <ul>
          <li><%= msg %></li>
        </ul>
      <% end %>
    </div>
  </div>
<% end %>

app/views/topics/_form.html.erb
<div class='well'>
  <%= form_for @topic do |f| %>
    <div class='content-group'>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class='content-group'>
      <%= f.label :content %>
      <%= f.text_area :content, rows: 5 %>
    </div>

    <div class='content-group'>
      <%= f.label :categories %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |c| %>
        <%= c.label(class: "checkbox inline") { c.check_box(class: "checkbox") + c.text} %>
      <% end %>
    </div>

    <%= f.submit(@topic.new_record? ? 'Create' : 'Save', class: 'btn btn-primary') %>
  <% end %>
</div>

app/views/topics/_topic.html.erb
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_topic_path(topic, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %> <br>
    <% end %>
    <span id="topic_<%= topic.id %>_vote"><%= pluralize(topic.total_votes,'vote') %></span><br>
    <% if logged_in? %>
      <%= link_to vote_topic_path(topic, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="well span8">
    <%= render topic.categories %>
    <h4><%= link_to topic.title, topic %></h4>
    <p><%= topic.content %></p> 
    <p>
      <span class="quiet">created by</span> 
      <%= link_to topic.user.username, user_path(topic.user) %> 
      <small>at <%= topic.created_at %></small>
    </p>
    <small><span><%= link_to pluralize(topic.comments.size, "comment"), topic_path(topic) %></span></small>
  </div>
</div>

app/views/topics/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Topic' %>

<%= render 'shared/error', obj: @topic %>

<%= render 'form' %>

app/views/topics/index.html.erb
<%= render 'shared/content_title', title: 'All Topics' %>

<% @topics.each do |topic| %>
  <%= render 'topic', topic: topic %>
<% end %>

app/views/topics/new.html.erb
<%= render 'shared/content_title', title: 'New Topic' %>

<%= render 'shared/error', obj: @topic %>

<%= render 'form' %>

app/views/topics/show.html.erb
<%= render @topic.categories %>
<% if logged_in? && (current_user == @topic.user) %>
<p class='pull-right'>[<%= link_to 'edit this topic', edit_topic_path(@topic) %>]</p>
<% end %>

<%= render 'shared/content_title', title: @topic.title %>

<div class="well">
  <%= @topic.content %>
</div>

<hr>

<% if logged_in? %>
  <%= form_for [@topic, @comment] do |f| %>
    <%= render 'shared/error', obj: @comment %>
    <div class="content-group">
      <%= f.label :body, "Leave a comment:" %>
      <%= f.text_area :body, rows: 3, class: "span4" %>
    </div>
    
    <%= f.submit "Create comment", class: "btn btn-primary" %>
  <% end %>
<% end %>

<h5>Comments:</h5>
<% @topic.comments.reload.sort_by { |comment| comment.total_votes }.reverse.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/topics/vote.js.erb
<% if @vote.valid? %>
  $("#topic_<%= @topic.id %>_vote").html("<%= pluralize(@topic.total_votes,'vote') %>");
<% else %>
  alert("You can only vote for this post once!")
<% end %>

app/views/users/_form.html.erb
<div class="well">
  <%= form_for @user do |f| %>
    <%= render 'shared/error', obj: @user %>
    <div class="content-group">
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>

    <div class="content-group">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="content-group">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>

    <%= f.submit(@user.new_record? ? 'Create' : 'Update', class: 'btn btn-primary') %>
  <% end %>
<div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Edit profile' %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class=well>
  <dl class="dl-horizontal">
    <dt>Username: </dt>
    <dd><%= @user.username %></dd>
    <dt>Email: </dt>
    <dd><%= @user.email %></dd>
  </dl>
</div>